/**
 * CHMSU HireMe — Mock Data
 * Complete dataset for all pages and components.
 */

export const mockData = {
  /* ── User Profile ── */
  'user/profile': {
    name: 'Maria Santos',
    initials: 'MS',
    email: 'maria.santos@chmsu.edu.ph',
    role: 'Bachelor of Science in Information Technology Student',
    status: 'active_ojt', // 'active_ojt' | 'alumni'
    studentId: '2023-00142',
    program: 'Bachelor of Science in Information Technology',
    year: '4th Year',
  },

  /* ── Dashboard Stats ── */
  'dashboard/stats': {
    ojtHours: { value: 267, total: 800, label: 'OJT Hours' },
    jobMatches: { value: 14, label: 'Job Matches' },
    applications: { value: 5, label: 'Applications' },
    interviews: { value: 2, label: 'Upcoming Interviews' },
  },

  /* ── Recent Activities ── */
  'dashboard/activities': [
    { id: 1, type: 'application', title: 'Applied to Frontend Developer at TechCorp', time: '2 hours ago', icon: 'briefcase' },
    { id: 2, type: 'interview', title: 'Interview scheduled with DataFlow Inc.', time: '5 hours ago', icon: 'video' },
    { id: 3, type: 'feedback', title: 'Supervisor feedback received', time: '1 day ago', icon: 'message-square' },
    { id: 4, type: 'match', title: 'New job match: UI/UX Designer at CreativeLab', time: '2 days ago', icon: 'zap' },
    { id: 5, type: 'log', title: 'Daily OJT log submitted', time: '2 days ago', icon: 'file-text' },
  ],

  /* ── Profile / Portfolio ── */
  'profile': {
    coverColor: 'linear-gradient(135deg, #4A6CF7 0%, #6D8DFF 50%, #93B4FF 100%)',
    name: 'Maria Santos',
    initials: 'MS',
    headline: 'Bachelor of Science in Information Technology Student · Frontend Developer · UI/UX Enthusiast',
    bio: 'Passionate 4th year Bachelor of Science in Information Technology student at CHMSU with a focus on frontend development and user experience design. Currently completing OJT at TechCorp Solutions, building real-world web applications. I love turning complex problems into simple, beautiful, and intuitive designs.',
    location: 'Cebu City, Philippines',
    email: 'maria.santos@chmsu.edu.ph',
    studentId: '2023-00142',
    program: 'Bachelor of Science in Information Technology',
    year: '4th Year',
    status: 'active_ojt',
    connections: 142,
    profileViews: 38,
    links: [
      { label: 'GitHub', url: 'github.com/mariasantos' },
      { label: 'LinkedIn', url: 'linkedin.com/in/mariasantos' },
      { label: 'Portfolio Site', url: 'mariasantos.dev' },
    ],
  },

  'profile/education': [
    { id: 1, school: 'Carlos Hilado Memorial State University', degree: 'Bachelor of Science in Information Technology', year: '2022 – 2026', gpa: '1.50', description: 'Major in Web and Mobile Development. Dean\'s Lister for 6 consecutive semesters.', current: true },
    { id: 2, school: 'Cebu Science High School', degree: 'Science, Technology, Engineering & Mathematics', year: '2018 – 2022', gpa: '1.25', description: 'Graduated with Honors. Computer Club President.', current: false },
  ],

  'profile/experience': [
    { id: 1, role: 'Frontend Developer Intern', company: 'TechCorp Solutions', period: 'Jan 2026 – Present', type: 'OJT', description: 'Building responsive web applications using React and vanilla JavaScript. Collaborated on a dashboard redesign that improved user engagement by 34%.', skills: ['React', 'JavaScript', 'CSS', 'Git'], current: true },
    { id: 2, role: 'Freelance Web Developer', company: 'Self-employed', period: 'Jun 2025 – Dec 2025', type: 'Freelance', description: 'Designed and developed 5 client websites including an e-commerce store and a restaurant booking system.', skills: ['HTML', 'CSS', 'JavaScript', 'WordPress'], current: false },
    { id: 3, role: 'UI/UX Design Volunteer', company: 'GDSC CHMSU', period: 'Aug 2024 – May 2025', type: 'Volunteer', description: 'Led the design team for the university\'s Google Developer Student Club. Created event posters and the club website.', skills: ['Figma', 'Canva', 'UX Research'], current: false },
  ],

  'profile/skills': [
    { name: 'JavaScript', level: 90, category: 'language', endorsed: 12 },
    { name: 'React', level: 80, category: 'framework', endorsed: 8 },
    { name: 'CSS / Sass', level: 92, category: 'language', endorsed: 10 },
    { name: 'HTML', level: 95, category: 'language', endorsed: 14 },
    { name: 'Node.js', level: 65, category: 'framework', endorsed: 5 },
    { name: 'Python', level: 55, category: 'language', endorsed: 3 },
    { name: 'Git', level: 85, category: 'tool', endorsed: 9 },
    { name: 'Figma', level: 78, category: 'tool', endorsed: 7 },
    { name: 'PostgreSQL', level: 60, category: 'database', endorsed: 4 },
    { name: 'TypeScript', level: 50, category: 'language', endorsed: 2 },
  ],

  'profile/achievements': [
    { id: 1, title: 'Dean\'s Lister', description: '6 consecutive semesters', type: 'academic', icon: 'award', date: '2022 – 2025' },
    { id: 2, title: 'Best Capstone Project Proposal', description: 'CHMSU IT Department', type: 'academic', icon: 'star', date: 'Nov 2025' },
    { id: 3, title: 'Google Developer Bootcamp', description: 'Web Development Track — Completed all modules', type: 'certification', icon: 'checkCircle', date: 'Feb 2026' },
    { id: 4, title: '1st Place Hackathon', description: 'VisMin IT Inter-school Competition', type: 'competition', icon: 'award', date: 'Oct 2025' },
    { id: 5, title: 'Oracle Database Certification', description: 'Oracle Academy — Database Administration', type: 'certification', icon: 'checkCircle', date: 'Jan 2026' },
    { id: 6, title: 'OJT Performance Award', description: 'Outstanding Intern — TechCorp Solutions Q1', type: 'professional', icon: 'star', date: 'Mar 2026' },
  ],

  'profile/works': [
    { id: 1, title: 'E-Commerce Dashboard', description: 'Full-stack admin dashboard with analytics, inventory management, and real-time order tracking.', tags: ['React', 'Node.js', 'PostgreSQL'], color: '#4A6CF7', emoji: '📊' },
    { id: 2, title: 'Restaurant Booking App', description: 'Mobile-friendly reservation system with QR code check-in and table management.', tags: ['JavaScript', 'Firebase', 'CSS'], color: '#34C759', emoji: '🍽️' },
    { id: 3, title: 'GDSC Club Website', description: 'Responsive website for the Google Developer Student Club with event registration and blog.', tags: ['HTML', 'CSS', 'JavaScript'], color: '#FFB547', emoji: '🌐' },
    { id: 4, title: 'Weather Forecast App', description: 'Real-time weather data with 7-day forecast, location search, and animated weather icons.', tags: ['React', 'API Integration', 'CSS'], color: '#FF6B6B', emoji: '🌤️' },
    { id: 5, title: 'Student Portfolio Generator', description: 'Automated portfolio builder that pulls verified academic data and generates a shareable page.', tags: ['Vite', 'JavaScript', 'CSS'], color: '#6D8DFF', emoji: '🎨' },
    { id: 6, title: 'Task Management CLI', description: 'Terminal-based productivity tool with deadlines, priorities, and project grouping.', tags: ['Python', 'SQLite'], color: '#9CA3BF', emoji: '✅' },
  ],

  'profile/resume': {
    objective: 'Detail-oriented BSIT student seeking full-time frontend developer opportunities. Experienced in building responsive web applications with modern JavaScript frameworks. Strong foundation in UI/UX design principles and agile development.',
    hoursRendered: 267,
    totalHours: 800,
    currentGrade: '1.50',
    supervisorRating: 4.5,
  },

  /* ── Internal Jobs ── */
  'jobs/internal': [
    {
      id: 1,
      title: 'Junior Frontend Developer',
      company: 'TechCorp Solutions',
      companyInitial: 'T',
      location: 'Cebu City',
      type: 'Full-time',
      salary: '₱25,000 - ₱35,000',
      matchScore: 92,
      matchExplanation: 'Strong match: Web Development, UI/UX Design, and JavaScript skills align with requirements',
      description: 'Build and maintain responsive web applications using modern frameworks. Collaborate with UI/UX team on design implementation.',
      skills: ['JavaScript', 'React', 'CSS', 'HTML', 'Git'],
      matchedSkills: ['JavaScript', 'CSS', 'HTML', 'Git'],
      postedDate: '3 days ago',
    },
    {
      id: 2,
      title: 'Full Stack Developer',
      company: 'DataFlow Inc.',
      companyInitial: 'D',
      location: 'Remote',
      type: 'Full-time',
      salary: '₱30,000 - ₱45,000',
      matchScore: 85,
      matchExplanation: 'Good match: Database Management and API Integration experience align well',
      description: 'Develop scalable backend services and integrate with frontend applications. Experience with Node.js preferred.',
      skills: ['Node.js', 'PostgreSQL', 'React', 'Docker', 'REST APIs'],
      matchedSkills: ['PostgreSQL', 'React', 'REST APIs'],
      postedDate: '1 week ago',
    },
    {
      id: 3,
      title: 'UI/UX Designer',
      company: 'CreativeLab Studio',
      companyInitial: 'C',
      location: 'Cebu City',
      type: 'Part-time',
      salary: '₱18,000 - ₱25,000',
      matchScore: 78,
      matchExplanation: 'Moderate match: UI/UX Design competency matches, design tool experience needed',
      description: 'Design user interfaces and create prototypes for web and mobile apps. Conduct user research and usability testing.',
      skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping', 'CSS'],
      matchedSkills: ['CSS'],
      postedDate: '2 weeks ago',
    },
  ],

  /* ── External Jobs ── */
  'jobs/external': [
    {
      id: 101,
      title: 'Software Engineer Intern',
      company: 'Google Philippines',
      companyInitial: 'G',
      location: 'Manila',
      type: 'Internship',
      source: 'LinkedIn',
      relevanceScore: 'High',
      description: 'Join our engineering team to build products that impact billions of users. Work on real projects from day one.',
      skills: ['Python', 'JavaScript', 'Data Structures', 'Algorithms'],
      matchedSkills: ['JavaScript'],
    },
    {
      id: 102,
      title: 'Web Developer',
      company: 'Accenture PH',
      companyInitial: 'A',
      location: 'Cebu City',
      type: 'Full-time',
      source: 'JobStreet',
      relevanceScore: 'Medium',
      description: 'Develop and maintain web applications for enterprise clients. Exposure to various tech stacks and industries.',
      skills: ['HTML', 'CSS', 'JavaScript', 'Angular', 'TypeScript'],
      matchedSkills: ['HTML', 'CSS', 'JavaScript'],
    },
  ],

  /* ── Applications ── */
  'applications': [
    { id: 1, title: 'Junior Frontend Developer', company: 'TechCorp Solutions', companyInitial: 'T', status: 'interview', appliedDate: 'Mar 12, 2026' },
    { id: 2, title: 'Full Stack Developer', company: 'DataFlow Inc.', companyInitial: 'D', status: 'reviewed', appliedDate: 'Mar 10, 2026' },
    { id: 3, title: 'Web Developer', company: 'Accenture PH', companyInitial: 'A', status: 'applied', appliedDate: 'Mar 8, 2026' },
    { id: 4, title: 'Software Engineer Intern', company: 'Google Philippines', companyInitial: 'G', status: 'offered', appliedDate: 'Feb 28, 2026' },
    { id: 5, title: 'IT Support Specialist', company: 'PLDT Enterprise', companyInitial: 'P', status: 'applied', appliedDate: 'Mar 15, 2026' },
  ],

  /* ── OJT Browsing (State 1) ── */
  'ojt/student-status': 'browsing',

  'ojt/eligibility': {
    status: 'eligible', // 'eligible' | 'pending' | 'not_eligible'
    reason: null,
    checklist: [
      { label: 'Units Completed', value: '108 / 120 units', done: true },
      { label: 'Pre-OJT Subjects Passed', value: 'All required subjects passed', done: true },
      { label: 'OJT Application Form', value: 'Submitted to CIER', done: true },
      { label: 'Medical Certificate', value: 'Not yet submitted', done: false },
      { label: 'Parent / Guardian Consent Form', value: 'Not yet submitted', done: false },
    ],
  },

  'ojt/slots': [
    {
      id: 1,
      slotTitle: 'IT Support & Web Development Intern',
      company: 'TechCorp Solutions',
      companyInitial: 'T',
      companyColor: '#4A6CF7',
      companyDesc: 'TechCorp Solutions is a leading software development company based in Bacolod City, providing enterprise IT solutions and web development services to SMEs and corporations across Western Visayas.',
      department: 'IT Department',
      industry: 'Information Technology',
      scheduleType: 'full_day',
      schedule: 'Mon–Fri · Full Day (8AM–5PM)',
      duration: '5 months (800 hours)',
      location: 'Bacolod City, Negros Occidental',
      mapLat: 10.6766,
      mapLon: 122.9498,
      slots: 5,
      slotsRemaining: 3,
      status: 'open',
      preferredCourses: ['BSIT', 'BSCS'],
      requiredSkills: ['HTML/CSS', 'JavaScript', 'Basic networking'],
      tasks: 'Web application support, database management, IT helpdesk assistance, system documentation, and user support for internal business tools.',
      learningOutcomes: 'Students will gain hands-on experience in full-stack web development, IT infrastructure management, and professional software development workflows.',
      requirements: ['OJT endorsement letter from school', 'Parent/guardian consent form', 'Medical certificate', 'NBI or police clearance'],
      contactName: 'Engr. Mark Rivera',
      postedDate: 'Apr 10, 2026',
      description: 'Join our IT team to work on real-world web applications, provide system support, and gain practical experience with modern development workflows in a professional environment.',
    },
    {
      id: 2,
      slotTitle: 'Accounting & Finance Trainee',
      company: 'GreenLeaf Corp',
      companyInitial: 'G',
      companyColor: '#10B981',
      companyDesc: 'GreenLeaf Corp is a regional distribution company in Bacolod specializing in agricultural products and sustainable supply chain management solutions.',
      department: 'Finance Department',
      industry: 'Finance & Accounting',
      scheduleType: 'full_day',
      schedule: 'Mon–Fri · Full Day (8AM–5PM)',
      duration: '5 months (800 hours)',
      location: 'Bacolod City, Negros Occidental',
      mapLat: 10.6803,
      mapLon: 122.9560,
      slots: 3,
      slotsRemaining: 1,
      status: 'filling_up',
      preferredCourses: ['BSA', 'BSBA'],
      requiredSkills: ['MS Excel', 'Bookkeeping basics'],
      tasks: 'Assist in accounts payable/receivable processing, financial report preparation, petty cash management, and filing of financial and accounting documents.',
      learningOutcomes: 'Trainees will develop practical skills in bookkeeping, financial reporting, and accounting software used in professional environments.',
      requirements: ['OJT endorsement letter', 'Parent consent form', 'Medical certificate'],
      contactName: 'Ms. Lorena Buenaventura',
      postedDate: 'Apr 5, 2026',
      description: 'Work alongside our finance team to gain practical experience in accounting procedures, bookkeeping, and financial record management for a regional distribution company.',
    },
    {
      id: 3,
      slotTitle: 'Marketing & Digital Media Intern',
      company: 'CreativeLab PH',
      companyInitial: 'C',
      companyColor: '#F59E0B',
      companyDesc: 'CreativeLab PH is a digital marketing agency creating campaigns for local and national brands, specializing in social media management and creative content production.',
      department: 'Marketing Department',
      industry: 'Marketing & Analytics',
      scheduleType: 'half_day',
      schedule: 'Mon–Fri · Half Day AM (8AM–12PM)',
      duration: '5 months (800 hours)',
      location: 'Bacolod City, Negros Occidental',
      mapLat: 10.6700,
      mapLon: 122.9480,
      slots: 4,
      slotsRemaining: 4,
      status: 'open',
      preferredCourses: ['BSBA', 'BSEd', 'Any'],
      requiredSkills: ['Social media literacy', 'Basic Canva / design tools'],
      tasks: 'Create social media content, assist in campaign planning and coordination, conduct market research, and manage content calendars for various clients.',
      learningOutcomes: 'Trainees will learn digital marketing strategies, content creation pipelines, client communication, and performance analytics reporting.',
      requirements: ['OJT endorsement letter', 'Parent consent form', 'Medical certificate'],
      contactName: 'Ms. Ella Guzman',
      postedDate: 'Apr 12, 2026',
      description: 'Be part of our creative team producing digital campaigns, managing social media accounts, and creating engaging content for a diverse portfolio of clients.',
    },
    {
      id: 4,
      slotTitle: 'HR & Administrative Support Trainee',
      company: 'Meridian BPO',
      companyInitial: 'M',
      companyColor: '#8B5CF6',
      companyDesc: 'Meridian BPO is a business process outsourcing company with over 500 employees, providing customer service solutions and back-office operations support to international clients.',
      department: 'Human Resources',
      industry: 'Information Technology',
      scheduleType: 'full_day',
      schedule: 'Mon–Fri · Full Day (8AM–5PM)',
      duration: '5 months (800 hours)',
      location: 'Silay City, Negros Occidental',
      mapLat: 10.7969,
      mapLon: 122.9748,
      slots: 6,
      slotsRemaining: 5,
      status: 'open',
      preferredCourses: ['BSBA', 'BSIT', 'Any'],
      requiredSkills: ['Communication skills', 'MS Office proficiency'],
      tasks: 'Assist in recruitment coordination, maintain employee records, support onboarding procedures, and handle internal administrative communications.',
      learningOutcomes: 'Trainees will gain exposure to HR operations, recruitment processes, employee relations, and professional workplace communication standards.',
      requirements: ['OJT endorsement letter', 'Parent consent form', 'Medical certificate', 'NBI clearance'],
      contactName: 'Mr. Ronaldo Campos',
      postedDate: 'Mar 28, 2026',
      description: 'Support our HR team in daily operations including recruitment coordination, employee record management, onboarding support, and administrative tasks in a large BPO setting.',
    },
    {
      id: 5,
      slotTitle: 'Software QA & Testing Intern',
      company: 'DataFlow Inc.',
      companyInitial: 'D',
      companyColor: '#EF4444',
      companyDesc: 'DataFlow Inc. is a technology company specializing in data analytics platforms, software quality assurance, and enterprise software solutions for financial institutions.',
      department: 'IT Department',
      industry: 'Information Technology',
      scheduleType: 'full_day',
      schedule: 'Mon–Fri · Full Day (8AM–5PM)',
      duration: '5 months (800 hours)',
      location: 'Bacolod City, Negros Occidental',
      mapLat: 10.6840,
      mapLon: 122.9500,
      slots: 2,
      slotsRemaining: 0,
      status: 'closed',
      preferredCourses: ['BSIT', 'BSCS', 'BSCpE'],
      requiredSkills: ['Basic programming knowledge', 'Analytical thinking'],
      tasks: 'Execute test cases, document and track software bugs, conduct regression testing, and assist in preparing test plans for enterprise web applications.',
      learningOutcomes: 'Trainees will learn software quality assurance methodologies, bug tracking tools, and professional testing documentation practices.',
      requirements: ['OJT endorsement letter', 'Parent consent form', 'Medical certificate'],
      contactName: 'Mr. Kenneth Lim',
      postedDate: 'Mar 15, 2026',
      description: 'Work with our QA team to test enterprise applications, write detailed test cases, and ensure software quality through systematic and structured testing processes.',
    },
  ],

  /* ── OJT Tracker Time Logs ── */
  'ojt/time-logs': [
    { id: 1,  date: 'Apr 18, 2026', dayLabel: 'Fri Apr 18', timeIn: '8:02 AM', timeOut: '5:03 PM', hours: 8.0, status: 'verified' },
    { id: 2,  date: 'Apr 17, 2026', dayLabel: 'Thu Apr 17', timeIn: '8:00 AM', timeOut: '5:00 PM', hours: 8.0, status: 'verified' },
    { id: 3,  date: 'Apr 16, 2026', dayLabel: 'Wed Apr 16', timeIn: '8:05 AM', timeOut: '5:00 PM', hours: 7.9, status: 'verified' },
    { id: 4,  date: 'Apr 15, 2026', dayLabel: 'Tue Apr 15', timeIn: '8:00 AM', timeOut: '5:00 PM', hours: 8.0, status: 'pending' },
    { id: 5,  date: 'Apr 14, 2026', dayLabel: 'Mon Apr 14', timeIn: '8:03 AM', timeOut: '5:02 PM', hours: 8.0, status: 'verified' },
    { id: 6,  date: 'Apr 11, 2026', dayLabel: 'Fri Apr 11', timeIn: '8:01 AM', timeOut: '5:00 PM', hours: 8.0, status: 'verified' },
    { id: 7,  date: 'Apr 10, 2026', dayLabel: 'Thu Apr 10', timeIn: '8:00 AM', timeOut: '5:00 PM', hours: 8.0, status: 'verified' },
    { id: 8,  date: 'Apr 9, 2026',  dayLabel: 'Wed Apr 9',  timeIn: '8:05 AM', timeOut: '5:00 PM', hours: 7.9, status: 'verified' },
    { id: 9,  date: 'Apr 8, 2026',  dayLabel: 'Tue Apr 8',  timeIn: '8:00 AM', timeOut: '5:00 PM', hours: 8.0, status: 'verified' },
    { id: 10, date: 'Apr 7, 2026',  dayLabel: 'Mon Apr 7',  timeIn: '8:00 AM', timeOut: '12:00 PM', hours: 4.0, status: 'verified' },
  ],

  /* ── OJT Data ── */
  'ojt/progress': {
    hoursRendered: 267,
    totalHours: 500,
    daysCompleted: 45,
    totalDays: 90,
    company: 'TechCorp Solutions',
    supervisor: 'Engr. Juan Dela Cruz',
    startDate: 'Jan 6, 2026',
    endDate: 'Jun 30, 2026',
    location: 'Bacolod City, Negros Occidental',
    companyAddress: 'Bac-Man Building, Lacson Street, Bacolod City, Negros Occidental 6100',
    mapLat: 10.6766,
    mapLon: 122.9511,
  },

  'ojt/logs': [
    { id: 1, date: 'Mar 19, 2026', hours: 8, tasks: 'Implemented responsive navbar component', status: 'approved' },
    { id: 2, date: 'Mar 18, 2026', hours: 8, tasks: 'Fixed API integration bugs in user dashboard', status: 'approved' },
    { id: 3, date: 'Mar 17, 2026', hours: 8, tasks: 'Conducted code review and documentation', status: 'pending' },
  ],

  'ojt/feedback': [
    { id: 1, supervisor: 'Engr. Juan Dela Cruz', initials: 'JD', rating: 5, comment: 'Excellent work on the dashboard redesign. Maria shows strong initiative and attention to detail.', date: 'Mar 15, 2026' },
    { id: 2, supervisor: 'Ms. Ana Reyes', initials: 'AR', rating: 4, comment: 'Good progress on the API integration. Keep improving test coverage.', date: 'Mar 8, 2026' },
    { id: 3, supervisor: 'Engr. Juan Dela Cruz', initials: 'JD', rating: 5, comment: 'Outstanding collaboration with the team on the mobile-first redesign project.', date: 'Mar 1, 2026' },
  ],

  /* ── Alumni Data ── */
  'alumni/certificates': [
    { id: 1, title: 'OJT Completion Certificate', issuer: 'CHMSU', date: 'Mar 2026', type: 'official' },
    { id: 2, title: 'Web Development Bootcamp', issuer: 'Google Developers', date: 'Feb 2026', type: 'training' },
    { id: 3, title: 'Database Administration', issuer: 'Oracle Academy', date: 'Jan 2026', type: 'certification' },
  ],

  'alumni/career-recommendations': [
    { id: 1, title: 'Full Stack Developer', description: 'Your combined frontend and backend skills make you an ideal candidate for full-stack roles in growing tech companies.', matchLevel: '95% career fit' },
    { id: 2, title: 'UI/UX Engineer', description: 'Your design sensibility and technical skills position you perfectly for engineering roles that bridge design and development.', matchLevel: '88% career fit' },
    { id: 3, title: 'Technical Project Manager', description: 'Leadership qualities observed during OJT, combined with technical background, suit project management paths.', matchLevel: '76% career fit' },
    { id: 4, title: 'DevOps Engineer', description: 'Experience with version control and deployment pipelines opens paths in cloud infrastructure and DevOps.', matchLevel: '70% career fit' },
  ],

  'alumni/network': [
    { id: 1, name: 'Carlo Reyes', initials: 'CR', role: 'Software Developer', company: 'Accenture PH', batch: '2024' },
    { id: 2, name: 'Ana Marie Tan', initials: 'AT', role: 'UI/UX Designer', company: 'Canva', batch: '2023' },
    { id: 3, name: 'Miguel Santos', initials: 'MS', role: 'Data Analyst', company: 'Thinking Machines', batch: '2024' },
    { id: 4, name: 'Patricia Lim', initials: 'PL', role: 'Web Developer', company: 'Freelance', batch: '2023' },
    { id: 5, name: 'Rafael Cruz', initials: 'RC', role: 'Systems Admin', company: 'Globe Telecom', batch: '2022' },
    { id: 6, name: 'Jessica Flores', initials: 'JF', role: 'Mobile Developer', company: 'Kumu', batch: '2024' },
  ],

  /* ── Students Network (People You Know) ── */
  'students/people-you-know': {
    data: [
      { id: 2,  name: 'Juan dela Cruz',   initials: 'JD', program: 'Bachelor of Science in Computer Science',        year: '4th Year' },
      { id: 3,  name: 'Ana Reyes',        initials: 'AR', program: 'Bachelor of Science in Information Technology', year: '3rd Year' },
      { id: 4,  name: 'Carlo Mendoza',    initials: 'CM', program: 'Bachelor of Science in Computer Engineering',    year: '4th Year' },
      { id: 6,  name: 'Mark Villanueva',  initials: 'MV', program: 'Bachelor of Science in Information Technology', year: '4th Year' },
      { id: 8,  name: 'Roberto Tan',      initials: 'RT', program: 'Bachelor of Science in Information Technology', year: '3rd Year' },
      { id: 9,  name: 'Patricia Aquino',  initials: 'PA', program: 'Bachelor of Science in Information Systems',     year: '4th Year' },
      { id: 10, name: 'Angelo Rivera',    initials: 'AR', program: 'Bachelor of Science in Computer Engineering',    year: '4th Year' },
      { id: 12, name: 'Rafael Navarro',   initials: 'RN', program: 'Bachelor of Science in Computer Science',        year: '4th Year' },
      { id: 13, name: 'Liza Fernandez',   initials: 'LF', program: 'Bachelor of Science in Information Technology', year: '3rd Year' },
    ],
    total: 9,
  },

  /* ── Interview Data ── */
  'interviews': [
    {
      id: 1,
      title: 'Technical Interview',
      company: 'TechCorp Solutions',
      companyInitial: 'T',
      date: 'Apr 2, 2026',
      time: '10:00 AM',
      duration: '45 min',
      platform: 'Google Meet',
      meetingLink: 'https://meet.google.com/abc-defg-hij',
      status: 'upcoming',
      interviewerName: 'Engr. Mark Rivera',
    },
    {
      id: 2,
      title: 'HR Screening',
      company: 'DataFlow Inc.',
      companyInitial: 'D',
      date: 'Apr 5, 2026',
      time: '2:00 PM',
      duration: '30 min',
      platform: 'Zoom',
      meetingLink: 'https://zoom.us/j/1234567890',
      status: 'upcoming',
      interviewerName: 'Ms. Sarah Chen',
    },
    {
      id: 3,
      title: 'Final Panel Interview',
      company: 'TechCorp Solutions',
      companyInitial: 'T',
      date: 'Apr 10, 2026',
      time: '9:00 AM',
      duration: '1 hour',
      platform: 'Microsoft Teams',
      meetingLink: 'https://teams.microsoft.com/l/meetup-join/abc123',
      status: 'upcoming',
      interviewerName: 'CTO Panel',
    },
  ],

  'interviews/schedule': [
    { id: 1, time: '10:00 AM', title: 'Technical Interview — TechCorp', detail: 'Focus: Frontend skills, coding challenge', current: true },
    { id: 2, time: '11:30 AM', title: 'Portfolio Review', detail: 'Prepare portfolio presentation', current: false },
    { id: 3, time: '2:00 PM', title: 'HR Screening — DataFlow', detail: 'Behavioral questions, salary discussion', current: false },
    { id: 4, time: '4:00 PM', title: 'Follow-up Email', detail: 'Send thank-you notes', current: false },
  ],
};
