/**
 * CHMSU HireMe — Company Portal Mock Data
 * Complete dataset for all company pages and components.
 */

export const mockData = {
  /* ── Company Profile ── */
  'company/profile': {
    name: 'TechCorp Solutions',
    initials: 'TC',
    industry: 'Information Technology',
    location: 'Cebu City, Philippines',
    employees: '50-200',
    founded: '2018',
    website: 'techcorp.ph',
    description: 'TechCorp Solutions is a leading IT services company specializing in web development, mobile applications, and cloud infrastructure for businesses across the Philippines.',
  },

  /* ── Dashboard Stats ── */
  'dashboard/stats': {
    activeJobs: 8,
    totalApplicants: 147,
    interviewsScheduled: 12,
    hiresThisMonth: 5,
  },

  /* ── Per-company dashboard data (keyed by company id) ── */
  'dashboard/by-company': {
    1: { // TechCorp Solutions
      stats: { activeJobs: 8, totalApplicants: 147, interviewsScheduled: 12, hiresThisMonth: 5 },
      hiringFunnel: { applied: 147, screened: 89, interviewed: 34, offered: 12, hired: 5 },
      todayInterviews: [
        { id: 1, candidateName: 'Maria Santos', candidateInitials: 'MS', jobTitle: 'Junior Frontend Developer', type: 'Technical Interview', time: '10:00 AM', platform: 'Google Meet', status: 'upcoming' },
        { id: 2, candidateName: 'Miguel Santos', candidateInitials: 'MiS', jobTitle: 'Full Stack Developer', type: 'HR Screening', time: '2:00 PM', platform: 'Zoom', status: 'upcoming' },
        { id: 3, candidateName: 'Patricia Lim', candidateInitials: 'PL', jobTitle: 'UI/UX Designer', type: 'Portfolio Review', time: '4:00 PM', platform: 'Google Meet', status: 'pending' },
      ],
      recentApplicants: [
        { id: 1, name: 'Maria Santos', initials: 'MS', appliedFor: 'Junior Frontend Developer', status: 'interview', matchScore: 92, appliedDate: 'Apr 10, 2026' },
        { id: 2, name: 'Carlo Reyes', initials: 'CR', appliedFor: 'Junior Frontend Developer', status: 'reviewed', matchScore: 85, appliedDate: 'Apr 10, 2026' },
        { id: 3, name: 'Jessica Flores', initials: 'JF', appliedFor: 'Junior Frontend Developer', status: 'applied', matchScore: 72, appliedDate: 'Apr 12, 2026' },
        { id: 4, name: 'Ana Tan', initials: 'AT', appliedFor: 'Full Stack Developer', status: 'hired', matchScore: 95, appliedDate: 'Apr 8, 2026' },
        { id: 5, name: 'Rafael Cruz', initials: 'RC', appliedFor: 'Full Stack Developer', status: 'reviewed', matchScore: 80, appliedDate: 'Apr 11, 2026' },
      ],
      monthlyApplications: [
        { month: 'Oct', count: 42 }, { month: 'Nov', count: 58 }, { month: 'Dec', count: 35 },
        { month: 'Jan', count: 67 }, { month: 'Feb', count: 91 }, { month: 'Mar', count: 147 },
      ],
    },
    2: { // GreenLeaf Corp
      stats: { activeJobs: 4, totalApplicants: 63, interviewsScheduled: 6, hiresThisMonth: 2 },
      hiringFunnel: { applied: 63, screened: 38, interviewed: 14, offered: 5, hired: 2 },
      todayInterviews: [
        { id: 10, candidateName: 'Lara Dela Cruz', candidateInitials: 'LC', jobTitle: 'Accounting Trainee', type: 'HR Screening', time: '9:00 AM', platform: 'Zoom', status: 'upcoming' },
        { id: 11, candidateName: 'Ryan Soriano', candidateInitials: 'RS', jobTitle: 'Finance Intern', type: 'Final Interview', time: '3:00 PM', platform: 'Google Meet', status: 'upcoming' },
      ],
      recentApplicants: [
        { id: 10, name: 'Lara Dela Cruz', initials: 'LC', appliedFor: 'Accounting Trainee', status: 'interview', matchScore: 88, appliedDate: 'Apr 9, 2026' },
        { id: 11, name: 'Ryan Soriano', initials: 'RS', appliedFor: 'Finance Intern', status: 'reviewed', matchScore: 79, appliedDate: 'Apr 10, 2026' },
        { id: 12, name: 'Pia Gutierrez', initials: 'PG', appliedFor: 'Accounting Trainee', status: 'applied', matchScore: 70, appliedDate: 'Apr 14, 2026' },
      ],
      monthlyApplications: [
        { month: 'Oct', count: 12 }, { month: 'Nov', count: 18 }, { month: 'Dec', count: 9 },
        { month: 'Jan', count: 22 }, { month: 'Feb', count: 40 }, { month: 'Mar', count: 63 },
      ],
    },
    3: { // CreativeLab PH
      stats: { activeJobs: 3, totalApplicants: 55, interviewsScheduled: 4, hiresThisMonth: 1 },
      hiringFunnel: { applied: 55, screened: 30, interviewed: 10, offered: 4, hired: 1 },
      todayInterviews: [
        { id: 20, candidateName: 'Bea Navarro', candidateInitials: 'BN', jobTitle: 'Digital Marketing Intern', type: 'Portfolio Review', time: '11:00 AM', platform: 'Google Meet', status: 'upcoming' },
      ],
      recentApplicants: [
        { id: 20, name: 'Bea Navarro', initials: 'BN', appliedFor: 'Digital Marketing Intern', status: 'interview', matchScore: 90, appliedDate: 'Apr 11, 2026' },
        { id: 21, name: 'Kim Ramos', initials: 'KR', appliedFor: 'Content Creator', status: 'applied', matchScore: 74, appliedDate: 'Apr 13, 2026' },
      ],
      monthlyApplications: [
        { month: 'Oct', count: 8 }, { month: 'Nov', count: 14 }, { month: 'Dec', count: 6 },
        { month: 'Jan', count: 19 }, { month: 'Feb', count: 35 }, { month: 'Mar', count: 55 },
      ],
    },
  },

  /* ── Recent Activities ── */
  'dashboard/activities': [
    { id: 1, type: 'new-application', text: 'Maria Santos applied for Frontend Developer', time: '10 minutes ago' },
    { id: 2, type: 'interview', text: 'Interview with Carlo Reyes in 2 hours', time: '30 minutes ago' },
    { id: 3, type: 'hired', text: 'Ana Tan accepted the offer for UI/UX Designer', time: '2 hours ago' },
    { id: 4, type: 'job-posted', text: 'New job post "Backend Developer" went live', time: '5 hours ago' },
    { id: 5, type: 'review', text: 'Miguel Santos portfolio review completed', time: '1 day ago' },
  ],

  /* ── Job Postings ── */
  'jobs': [
    {
      id: 1,
      title: 'Junior Frontend Developer',
      department: 'Engineering',
      location: 'Cebu City',
      type: 'Full-time',
      salary: '₱25,000 - ₱35,000',
      status: 'active',
      applicants: 34,
      posted: 'Mar 15, 2026',
      expires: 'Apr 15, 2026',
      description: 'We are looking for a motivated Junior Frontend Developer to join our engineering team. You will work on building responsive, high-performance web applications using modern JavaScript frameworks.',
      responsibilities: [
        'Build and maintain responsive web applications using React',
        'Collaborate with UI/UX team on design implementation',
        'Write clean, maintainable, and well-tested code',
        'Participate in code reviews and team discussions',
        'Troubleshoot and debug production issues',
      ],
      requirements: [
        'Bachelor\'s degree in IT, Computer Science, or related field',
        'Proficiency in HTML, CSS, and JavaScript',
        'Experience with React or similar frameworks',
        'Understanding of RESTful APIs and version control (Git)',
        'Strong problem-solving skills and attention to detail',
      ],
      benefits: [
        'Competitive salary with performance bonuses',
        'Health insurance (HMO)',
        'Remote work flexibility',
        'Learning & development budget',
        'Team outings and company events',
      ],
      skills: ['JavaScript', 'React', 'CSS', 'HTML', 'Git'],
      applicantAvatars: [
        { initials: 'MS', name: 'Maria Santos' },
        { initials: 'CR', name: 'Carlo Reyes' },
        { initials: 'JF', name: 'Jessica Flores' },
      ],
    },
    {
      id: 2,
      title: 'Full Stack Developer',
      department: 'Engineering',
      location: 'Remote',
      type: 'Full-time',
      salary: '₱35,000 - ₱50,000',
      status: 'active',
      applicants: 28,
      posted: 'Mar 10, 2026',
      expires: 'Apr 10, 2026',
      description: 'Join our backend engineering team to build scalable microservices and API integrations. You\'ll work closely with frontend developers and DevOps to ship features end-to-end.',
      responsibilities: [
        'Design and implement scalable backend services',
        'Build and maintain RESTful APIs',
        'Optimize database queries and data models',
        'Collaborate with the frontend team for integration',
        'Implement CI/CD pipelines and automated testing',
      ],
      requirements: [
        'Experience with Node.js, Python, or similar',
        'Proficiency with PostgreSQL or MongoDB',
        'Understanding of containerization (Docker)',
        'Knowledge of cloud services (AWS/GCP)',
        'Strong analytical and communication skills',
      ],
      benefits: [
        'Fully remote work environment',
        'Competitive compensation package',
        'Stock options program',
        'Annual tech equipment allowance',
        'Unlimited PTO policy',
      ],
      skills: ['Node.js', 'PostgreSQL', 'React', 'Docker', 'AWS'],
      applicantAvatars: [
        { initials: 'AT', name: 'Ana Tan' },
        { initials: 'RC', name: 'Rafael Cruz' },
      ],
    },
    {
      id: 3,
      title: 'UI/UX Designer',
      department: 'Design',
      location: 'Cebu City',
      type: 'Part-time',
      salary: '₱18,000 - ₱25,000',
      status: 'active',
      applicants: 19,
      posted: 'Mar 18, 2026',
      expires: 'Apr 18, 2026',
      description: 'We need a creative UI/UX Designer to craft beautiful, user-centered interfaces. You\'ll collaborate with product managers and engineers to bring designs from concept to production.',
      responsibilities: [
        'Create wireframes, prototypes, and high-fidelity designs',
        'Conduct user research and usability testing',
        'Develop and maintain the design system',
        'Collaborate with developers on implementation',
        'Present design solutions to stakeholders',
      ],
      requirements: [
        'Proficiency in Figma and design tools',
        'Portfolio demonstrating UI/UX work',
        'Understanding of design principles and accessibility',
        'Basic knowledge of HTML/CSS',
        'Strong communication skills',
      ],
      benefits: [
        'Flexible part-time schedule',
        'Creative work environment',
        'Access to design tools and resources',
        'Portfolio-building projects',
        'Path to full-time conversion',
      ],
      skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping', 'CSS'],
      applicantAvatars: [
        { initials: 'PL', name: 'Patricia Lim' },
      ],
    },
    {
      id: 4,
      title: 'DevOps Engineer',
      department: 'Infrastructure',
      location: 'Remote',
      type: 'Full-time',
      salary: '₱40,000 - ₱60,000',
      status: 'draft',
      applicants: 0,
      posted: null,
      expires: null,
      description: 'We are hiring a DevOps Engineer to manage our cloud infrastructure, automate deployment pipelines, and ensure the reliability of our production systems.',
      responsibilities: [
        'Manage AWS cloud infrastructure and services',
        'Build and maintain CI/CD pipelines',
        'Monitor system performance and uptime',
        'Implement security best practices',
        'Automate repetitive operational tasks',
      ],
      requirements: [
        'Experience with AWS, GCP, or Azure',
        'Proficiency with Docker and Kubernetes',
        'Knowledge of Terraform or similar IaC tools',
        'Understanding of networking and security',
        'Experience with monitoring tools (Datadog, Grafana)',
      ],
      benefits: [
        'Fully remote work',
        'Premium compensation',
        'Conference attendance budget',
        'Certification sponsorship',
        'Flex Fridays',
      ],
      skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'Linux'],
      applicantAvatars: [],
    },
    {
      id: 5,
      title: 'QA Tester',
      department: 'Quality Assurance',
      location: 'Cebu City',
      type: 'Full-time',
      salary: '₱20,000 - ₱30,000',
      status: 'closed',
      applicants: 42,
      posted: 'Feb 1, 2026',
      expires: 'Mar 1, 2026',
      description: 'We are looking for a detail-oriented QA Tester to ensure the quality of our software products through manual and automated testing.',
      responsibilities: [
        'Write and execute test cases and test plans',
        'Perform manual and automated testing',
        'Report and track bugs using JIRA',
        'Collaborate with developers to resolve issues',
        'Ensure product quality before release',
      ],
      requirements: [
        'Experience with software testing methodologies',
        'Familiarity with test automation tools',
        'Attention to detail and analytical mindset',
        'Basic understanding of web technologies',
        'Good written communication skills',
      ],
      benefits: [
        'Competitive salary',
        'Health insurance',
        'Career development programs',
        'Team activities and events',
        'Modern office space',
      ],
      skills: ['Manual Testing', 'Selenium', 'JIRA', 'SQL', 'Agile'],
      applicantAvatars: [],
    },
  ],

  /* ── Applicants ── */
  'applicants': [
    {
      id: 1,
      name: 'Maria Santos',
      initials: 'MS',
      email: 'maria.santos@chmsu.edu.ph',
      location: 'Cebu City',
      role: 'Bachelor of Science in Information Technology Student',
      program: 'Bachelor of Science in Information Technology',
      year: '4th Year',
      appliedFor: 'Junior Frontend Developer',
      jobId: 1,
      status: 'interview',
      matchScore: 92,
      appliedDate: 'Mar 16, 2026',
      skills: ['JavaScript', 'React', 'CSS', 'HTML', 'Git'],
      experience: '1 year (OJT + Freelance)',
      gpa: '1.50',
      notes: 'Strong portfolio with real-world projects. Excellent OJT performance.',
      rating: 4.5,
    },
    {
      id: 2,
      name: 'Carlo Reyes',
      initials: 'CR',
      email: 'carlo.reyes@chmsu.edu.ph',
      location: 'Talisay City',
      role: 'Bachelor of Science in Information Technology Student',
      program: 'Bachelor of Science in Information Technology',
      year: '4th Year',
      appliedFor: 'Junior Frontend Developer',
      jobId: 1,
      status: 'reviewed',
      matchScore: 85,
      appliedDate: 'Mar 17, 2026',
      skills: ['JavaScript', 'Vue.js', 'CSS', 'Node.js'],
      experience: '6 months (Freelance)',
      gpa: '1.75',
      notes: 'Good technical skills. Vue.js background is adaptable to React.',
      rating: 4,
    },
    {
      id: 3,
      name: 'Jessica Flores',
      initials: 'JF',
      email: 'jessica.flores@chmsu.edu.ph',
      location: 'Cebu City',
      role: 'Bachelor of Science in Information Technology Student',
      program: 'Bachelor of Science in Information Technology',
      year: '3rd Year',
      appliedFor: 'Junior Frontend Developer',
      jobId: 1,
      status: 'applied',
      matchScore: 72,
      appliedDate: 'Mar 20, 2026',
      skills: ['HTML', 'CSS', 'JavaScript', 'Figma'],
      experience: 'Academic projects only',
      gpa: '1.5',
      notes: '',
      rating: 0,
    },
    {
      id: 4,
      name: 'Ana Marie Tan',
      initials: 'AT',
      email: 'ana.tan@chmsu.edu.ph',
      location: 'Mandaue City',
      role: 'Bachelor of Science in Information Technology Student',
      program: 'Bachelor of Science in Information Technology',
      year: '4th Year',
      appliedFor: 'Full Stack Developer',
      jobId: 2,
      status: 'offered',
      matchScore: 88,
      appliedDate: 'Mar 12, 2026',
      skills: ['Node.js', 'React', 'PostgreSQL', 'Docker'],
      experience: '1.5 years (Freelance + OJT)',
      gpa: '1.25',
      notes: 'Outstanding candidate. Full stack experience. Offered ₱38,000.',
      rating: 5,
    },
    {
      id: 5,
      name: 'Miguel Santos',
      initials: 'MS',
      email: 'miguel.santos@chmsu.edu.ph',
      location: 'Lapu-Lapu City',
      role: 'Bachelor of Science in Computer Science Student',
      program: 'Bachelor of Science in Computer Science',
      year: '4th Year',
      appliedFor: 'Full Stack Developer',
      jobId: 2,
      status: 'interview',
      matchScore: 80,
      appliedDate: 'Mar 14, 2026',
      skills: ['Python', 'Django', 'PostgreSQL', 'React'],
      experience: '1 year (Research + Projects)',
      gpa: '1.50',
      notes: 'Strong algorithmic thinking. Good cultural fit.',
      rating: 4,
    },
    {
      id: 6,
      name: 'Patricia Lim',
      initials: 'PL',
      email: 'patricia.lim@chmsu.edu.ph',
      location: 'Cebu City',
      role: 'Bachelor of Science in Information Technology Student',
      program: 'Bachelor of Science in Information Technology',
      year: '4th Year',
      appliedFor: 'UI/UX Designer',
      jobId: 3,
      status: 'reviewed',
      matchScore: 90,
      appliedDate: 'Mar 19, 2026',
      skills: ['Figma', 'Adobe XD', 'CSS', 'User Research'],
      experience: '2 years (Freelance Design)',
      gpa: '1.50',
      notes: 'Impressive design portfolio. Strong UX research skills.',
      rating: 4.5,
    },
    {
      id: 7,
      name: 'Rafael Cruz',
      initials: 'RC',
      email: 'rafael.cruz@chmsu.edu.ph',
      location: 'Toledo City',
      role: 'Bachelor of Science in Information Technology Student',
      program: 'Bachelor of Science in Information Technology',
      year: '3rd Year',
      appliedFor: 'Full Stack Developer',
      jobId: 2,
      status: 'rejected',
      matchScore: 55,
      appliedDate: 'Mar 11, 2026',
      skills: ['PHP', 'MySQL', 'HTML'],
      experience: 'Academic projects',
      gpa: '2.00',
      notes: 'Does not meet minimum requirements for the role.',
      rating: 2,
    },
  ],

  /* ── Applications (Job & OJT Unified) ── */
  'applications': [
    {
      id: '1',
      raw_id: 1,
      category: 'job',
      category_label: 'Job Opening',
      status: 'interview',
      raw_status: 'interview',
      status_label: 'Interview',
      applied_at: 'Mar 16, 2026',
      match_score: 92,
      matched_skills: ['React', 'JavaScript', 'CSS', 'HTML'],
      interview_date: '2026-04-02',
      job: {
        id: 1,
        title: 'Junior Frontend Developer',
        required_skills: ['React', 'JavaScript', 'CSS', 'HTML'],
        salary_range: '₱25,000 - ₱35,000 / mo',
        company: 'TechCorp Solutions',
        is_ojt: false,
      },
      applicant: {
        id: 1,
        name: 'Maria Santos',
        initials: 'MS',
        email: 'maria.santos@chmsu.edu.ph',
        headline: 'Aspiring Frontend Developer · Bachelor of Science in Information Technology Graduate',
        location: 'Cebu City',
        phone: '0917-123-4567',
        avatar_url: null,
        skills: ['JavaScript', 'React', 'CSS', 'HTML', 'Git'],
        is_student: false,
      },
    },
    {
      id: 'ojt_101',
      raw_id: 101,
      category: 'ojt',
      category_label: 'OJT Internship',
      status: 'interview',
      raw_status: 'interview_scheduled',
      status_label: 'Interview Scheduled',
      applied_at: 'Mar 18, 2026',
      match_score: 88,
      matched_skills: ['QA Testing', 'Manual Testing', 'Bug Reporting'],
      interview_date: '2026-04-02',
      job: {
        id: 12,
        title: 'Software QA / Tester Intern',
        required_skills: ['QA Testing', 'Manual Testing', 'Bug Reporting'],
        salary_range: '₱6,000 / mo allowance',
        company: 'TechCorp Solutions',
        is_ojt: true,
      },
      applicant: {
        id: 101,
        name: 'Joshua Alcantara',
        initials: 'JA',
        email: 'joshua.alcantara@chmsu.edu.ph',
        headline: 'Bachelor of Science in Information Technology · 4th Year',
        location: 'Talisay City',
        phone: '0918-234-5678',
        avatar_url: null,
        skills: ['QA Testing', 'Manual Testing', 'Bug Reporting', 'Selenium'],
        is_student: true,
        program: 'Bachelor of Science in Information Technology',
        year_level: '4th Year',
      },
    },
    {
      id: 'ojt_102',
      raw_id: 102,
      category: 'ojt',
      category_label: 'OJT Internship',
      status: 'reviewed',
      raw_status: 'endorsed',
      status_label: 'Endorsed (Ready for Interview)',
      applied_at: 'Mar 19, 2026',
      match_score: 95,
      matched_skills: ['Vue.js', 'JavaScript', 'HTML5', 'CSS3'],
      interview_date: null,
      job: {
        id: 14,
        title: 'Frontend Web Developer Intern',
        required_skills: ['Vue.js', 'JavaScript', 'HTML5', 'CSS3'],
        salary_range: '₱7,500 / mo allowance',
        company: 'TechCorp Solutions',
        is_ojt: true,
      },
      applicant: {
        id: 102,
        name: 'Bea Villanueva',
        initials: 'BV',
        email: 'bea.villanueva@chmsu.edu.ph',
        headline: 'Bachelor of Science in Information Systems · 4th Year',
        location: 'Bacolod City',
        phone: '0919-345-6789',
        avatar_url: null,
        skills: ['Vue.js', 'JavaScript', 'HTML5', 'CSS3', 'Figma'],
        is_student: true,
        program: 'Bachelor of Science in Information Systems',
        year_level: '4th Year',
      },
    },
    {
      id: '2',
      raw_id: 2,
      category: 'job',
      category_label: 'Job Opening',
      status: 'reviewed',
      raw_status: 'reviewed',
      status_label: 'Under Review',
      applied_at: 'Mar 17, 2026',
      match_score: 85,
      matched_skills: ['JavaScript', 'Vue.js', 'CSS', 'Node.js'],
      interview_date: null,
      job: {
        id: 1,
        title: 'Junior Frontend Developer',
        required_skills: ['JavaScript', 'Vue.js', 'CSS', 'Node.js'],
        salary_range: '₱25,000 - ₱35,000 / mo',
        company: 'TechCorp Solutions',
        is_ojt: false,
      },
      applicant: {
        id: 2,
        name: 'Carlo Reyes',
        initials: 'CR',
        email: 'carlo.reyes@chmsu.edu.ph',
        headline: 'Frontend Engineer',
        location: 'Talisay City',
        phone: '0920-456-7890',
        avatar_url: null,
        skills: ['JavaScript', 'Vue.js', 'CSS', 'Node.js'],
        is_student: false,
      },
    },
    {
      id: '3',
      raw_id: 3,
      category: 'job',
      category_label: 'Job Opening',
      status: 'applied',
      raw_status: 'applied',
      status_label: 'Applied',
      applied_at: 'Mar 20, 2026',
      match_score: 72,
      matched_skills: ['HTML', 'CSS', 'JavaScript'],
      interview_date: null,
      job: {
        id: 1,
        title: 'Junior Frontend Developer',
        required_skills: ['HTML', 'CSS', 'JavaScript'],
        salary_range: '₱25,000 - ₱35,000 / mo',
        company: 'TechCorp Solutions',
        is_ojt: false,
      },
      applicant: {
        id: 3,
        name: 'Jessica Flores',
        initials: 'JF',
        email: 'jessica.flores@chmsu.edu.ph',
        headline: 'Junior Web Designer',
        location: 'Cebu City',
        phone: '0921-567-8901',
        avatar_url: null,
        skills: ['HTML', 'CSS', 'JavaScript', 'Figma'],
        is_student: false,
      },
    },
    {
      id: 'ojt_103',
      raw_id: 103,
      category: 'ojt',
      category_label: 'OJT Internship',
      status: 'applied',
      raw_status: 'interested',
      status_label: 'Applied',
      applied_at: 'Mar 21, 2026',
      match_score: 80,
      matched_skills: ['Network Configuration', 'Troubleshooting'],
      interview_date: null,
      job: {
        id: 15,
        title: 'IT Support & Systems Intern',
        required_skills: ['Network Configuration', 'Troubleshooting'],
        salary_range: 'Unpaid OJT',
        company: 'TechCorp Solutions',
        is_ojt: true,
      },
      applicant: {
        id: 103,
        name: 'Danilo Ramos',
        initials: 'DR',
        email: 'danilo.ramos@chmsu.edu.ph',
        headline: 'Bachelor of Science in Information Technology · 3rd Year',
        location: 'Silay City',
        phone: '0922-678-9012',
        avatar_url: null,
        skills: ['Network Configuration', 'Troubleshooting', 'Linux'],
        is_student: true,
        program: 'Bachelor of Science in Information Technology',
        year_level: '3rd Year',
      },
    },
    {
      id: '4',
      raw_id: 4,
      category: 'job',
      category_label: 'Job Opening',
      status: 'applied',
      raw_status: 'applied',
      status_label: 'Applied',
      applied_at: 'Mar 22, 2026',
      match_score: 33,
      matched_skills: ['HTML'],
      interview_date: null,
      job: {
        id: 1,
        title: 'Junior Frontend Developer',
        required_skills: ['React', 'JavaScript', 'CSS', 'HTML'],
        salary_range: '₱25,000 - ₱35,000 / mo',
        company: 'TechCorp Solutions',
        is_ojt: false,
      },
      applicant: {
        id: 4,
        name: 'Patrick James Lee',
        initials: 'PL',
        email: 'patrick.lee@chmsu.edu.ph',
        headline: 'Aspiring Web Developer',
        location: 'Bacolod City',
        phone: '0923-456-7891',
        avatar_url: null,
        skills: ['HTML', 'WordPress', 'Photoshop'],
        is_student: false,
      },
    },
    {
      id: 'ojt_104',
      raw_id: 104,
      category: 'ojt',
      category_label: 'OJT Internship',
      status: 'applied',
      raw_status: 'interested',
      status_label: 'Applied',
      applied_at: 'Mar 23, 2026',
      match_score: 0,
      matched_skills: [],
      interview_date: null,
      job: {
        id: 12,
        title: 'Software QA / Tester Intern',
        required_skills: ['QA Testing', 'Manual Testing', 'Bug Reporting'],
        salary_range: '₱6,000 / mo allowance',
        company: 'TechCorp Solutions',
        is_ojt: true,
      },
      applicant: {
        id: 104,
        name: 'Christian Gabriel Cruz',
        initials: 'CC',
        email: 'christian.cruz@chmsu.edu.ph',
        headline: 'Bachelor of Science in Hospitality Management · 3rd Year',
        location: 'Talisay City',
        phone: '0924-567-8902',
        avatar_url: null,
        skills: ['Customer Service', 'Food Safety'],
        is_student: true,
        program: 'Bachelor of Science in Hospitality Management',
        year_level: '3rd Year',
      },
    },
  ],

  /* ── Interviews ── */
  'interviews': [
    {
      id: '1',
      raw_id: 1,
      category: 'job',
      category_label: 'Job Opening',
      candidate: {
        name: 'Maria Santos',
        initials: 'MS',
        role: 'Junior Frontend Developer Applicant',
      },
      candidateName: 'Maria Santos',
      candidateInitials: 'MS',
      candidateRole: 'Junior Frontend Developer Applicant',
      job: {
        id: 1,
        title: 'Junior Frontend Developer',
        is_ojt: false,
      },
      jobTitle: 'Junior Frontend Developer',
      type: 'Technical Interview',
      interview_type: 'online',
      date: 'Apr 2, 2026',
      date_raw: '2026-04-02',
      time: '10:00 AM',
      duration: '45 min',
      platform: 'Google Meet',
      meeting_link: 'https://meet.google.com/abc-defg-hij',
      meetingLink: 'https://meet.google.com/abc-defg-hij',
      location: 'Google Meet',
      interviewer_name: 'Engr. Mark Rivera',
      interviewer: 'Engr. Mark Rivera',
      status: 'upcoming',
      notes: 'Focus on React proficiency and problem-solving. Review portfolio beforehand.',
    },
    {
      id: 'ojt_101',
      raw_id: 101,
      category: 'ojt',
      category_label: 'OJT Internship',
      candidate: {
        name: 'Joshua Alcantara',
        initials: 'JA',
        role: 'Bachelor of Science in Information Technology · 4th Year',
      },
      candidateName: 'Joshua Alcantara',
      candidateInitials: 'JA',
      candidateRole: 'Bachelor of Science in Information Technology · 4th Year',
      job: {
        id: 12,
        title: 'Software QA / Tester Intern',
        is_ojt: true,
      },
      jobTitle: 'Software QA / Tester Intern',
      type: 'Face-to-Face Interview',
      interview_type: 'face_to_face',
      date: 'Apr 2, 2026',
      date_raw: '2026-04-02',
      time: '11:30 AM',
      duration: '45 min',
      platform: 'On-site / In-person',
      meeting_link: '#',
      meetingLink: '#',
      location: 'Building 2, Engineering Dept, 3rd Floor Room 304',
      interviewer_name: 'Engr. Mark Rivera',
      interviewer: 'Engr. Mark Rivera',
      status: 'upcoming',
      notes: 'Bring endorsement letter from CHMSU coordinator and copy of resume.',
    },
    {
      id: '2',
      raw_id: 2,
      category: 'job',
      category_label: 'Job Opening',
      candidate: {
        name: 'Miguel Santos',
        initials: 'MS',
        role: 'Bachelor of Science in Computer Science Student · 4th Year',
      },
      candidateName: 'Miguel Santos',
      candidateInitials: 'MS',
      candidateRole: 'Bachelor of Science in Computer Science Student · 4th Year',
      job: {
        id: 2,
        title: 'Full Stack Developer',
        is_ojt: false,
      },
      jobTitle: 'Full Stack Developer',
      type: 'HR Screening',
      interview_type: 'online',
      date: 'Apr 2, 2026',
      date_raw: '2026-04-02',
      time: '2:00 PM',
      duration: '30 min',
      platform: 'Zoom',
      meeting_link: 'https://zoom.us/j/1234567890',
      meetingLink: 'https://zoom.us/j/1234567890',
      location: 'Zoom',
      interviewer_name: 'Ms. Sarah Chen',
      interviewer: 'Ms. Sarah Chen',
      status: 'upcoming',
      notes: 'Behavioral questions. Discuss salary expectations and availability.',
    },
    {
      id: 'ojt_102',
      raw_id: 102,
      category: 'ojt',
      category_label: 'OJT Internship',
      candidate: {
        name: 'Bea Villanueva',
        initials: 'BV',
        role: 'Bachelor of Science in Information Systems · 4th Year',
      },
      candidateName: 'Bea Villanueva',
      candidateInitials: 'BV',
      candidateRole: 'Bachelor of Science in Information Systems · 4th Year',
      job: {
        id: 14,
        title: 'Frontend Web Developer Intern',
        is_ojt: true,
      },
      jobTitle: 'Frontend Web Developer Intern',
      type: 'Online Interview',
      interview_type: 'online',
      date: 'Apr 4, 2026',
      date_raw: '2026-04-04',
      time: '10:00 AM',
      duration: '45 min',
      platform: 'Google Meet',
      meeting_link: 'https://meet.google.com/ojt-tech-test',
      meetingLink: 'https://meet.google.com/ojt-tech-test',
      location: 'https://meet.google.com/ojt-tech-test',
      interviewer_name: 'Tech Development Lead',
      interviewer: 'Tech Development Lead',
      status: 'upcoming',
      notes: 'Student endorsed by OJT Coordinator. Review GitHub portfolio.',
    },
    {
      id: '3',
      raw_id: 3,
      category: 'job',
      category_label: 'Job Opening',
      candidate: {
        name: 'Carlo Reyes',
        initials: 'CR',
        role: 'Bachelor of Science in Information Technology Student · 4th Year',
      },
      candidateName: 'Carlo Reyes',
      candidateInitials: 'CR',
      candidateRole: 'Bachelor of Science in Information Technology Student · 4th Year',
      job: {
        id: 1,
        title: 'Junior Frontend Developer',
        is_ojt: false,
      },
      jobTitle: 'Junior Frontend Developer',
      type: 'Final Panel Interview',
      interview_type: 'online',
      date: 'Apr 5, 2026',
      date_raw: '2026-04-05',
      time: '9:00 AM',
      duration: '1 hour',
      platform: 'Microsoft Teams',
      meeting_link: 'https://teams.microsoft.com/l/meetup-join/abc123',
      meetingLink: 'https://teams.microsoft.com/l/meetup-join/abc123',
      location: 'Microsoft Teams',
      interviewer_name: 'CTO Panel',
      interviewer: 'CTO Panel',
      status: 'upcoming',
      notes: 'Final round. Panel includes CTO, Engineering Lead, and HR Director.',
    },
    {
      id: '4',
      raw_id: 4,
      category: 'job',
      category_label: 'Job Opening',
      candidate: {
        name: 'Patricia Lim',
        initials: 'PL',
        role: 'Bachelor of Science in Information Technology Student · 4th Year',
      },
      candidateName: 'Patricia Lim',
      candidateInitials: 'PL',
      candidateRole: 'Bachelor of Science in Information Technology Student · 4th Year',
      job: {
        id: 3,
        title: 'UI/UX Designer',
        is_ojt: false,
      },
      jobTitle: 'UI/UX Designer',
      type: 'Portfolio Review',
      interview_type: 'online',
      date: 'Apr 7, 2026',
      date_raw: '2026-04-07',
      time: '11:00 AM',
      duration: '45 min',
      platform: 'Google Meet',
      meeting_link: 'https://meet.google.com/xyz-abcd-efg',
      meetingLink: 'https://meet.google.com/xyz-abcd-efg',
      location: 'Google Meet',
      interviewer_name: 'Lead Designer',
      interviewer: 'Lead Designer',
      status: 'upcoming',
      notes: 'Review Figma portfolio and design thinking process.',
    },
  ],

  'interviews/schedule': [
    { id: 1, time: '10:00 AM', title: 'Technical Interview — Maria Santos', detail: 'Frontend Developer · Google Meet', current: true },
    { id: 2, time: '2:00 PM', title: 'HR Screening — Miguel Santos', detail: 'Full Stack Developer · Zoom', current: false },
    { id: 3, time: '4:00 PM', title: 'Review applicant portfolios', detail: '3 portfolios pending review', current: false },
  ],

  /* ── OJT Slots ── */
  'ojt-slots': [
    {
      id: 1,
      department: 'IT Department',
      slots: 3,
      slotsRemaining: 2,
      preferredCourse: 'Bachelor of Science in Information Technology',
      duration: '3 months (486 hours)',
      schedule: 'Full Day · Mon–Fri',
      tasks: 'Web development support, database management, IT helpdesk, documentation, and software testing.',
      learningOutcomes: 'Students will gain hands-on experience in full-stack web development, database operations, and professional IT workflows.',
      requirements: ['Basic HTML/CSS/JavaScript knowledge', 'OJT endorsement letter from school', 'Parent consent form', 'Medical certificate'],
      supervisor: 'Engr. Mark Rivera',
      supervisorContact: 'mrivera@techcorp.ph',
      startDate: 'May 5, 2026',
      status: 'open',
      endorsed: 1,
      deployed: 1,
      posted: 'Apr 1, 2026',
    },
    {
      id: 2,
      department: 'Accounting Department',
      slots: 2,
      slotsRemaining: 2,
      preferredCourse: 'Bachelor of Science in Accountancy',
      duration: '6 months (240 hours)',
      schedule: 'Half Day (AM) · Mon–Sat',
      tasks: 'Financial record preparation, accounts payable/receivable assistance, bookkeeping, and audit support.',
      learningOutcomes: 'Students will develop practical accounting skills, use actual accounting software, and understand real business finance operations.',
      requirements: ['Bachelor of Science in Accountancy student', 'Minimum 2.0 GPA', 'OJT endorsement letter from school', 'Waiver form'],
      supervisor: 'Ms. Sarah Chen',
      supervisorContact: 'schen@techcorp.ph',
      startDate: 'May 12, 2026',
      status: 'open',
      endorsed: 0,
      deployed: 0,
      posted: 'Apr 3, 2026',
    },
    {
      id: 3,
      department: 'Human Resources',
      slots: 1,
      slotsRemaining: 0,
      preferredCourse: 'Bachelor of Science in Business Administration',
      duration: '3 months (486 hours)',
      schedule: 'Full Day · Mon–Fri',
      tasks: 'Recruitment assistance, employee records management, HR documentation, onboarding support, and payroll monitoring.',
      learningOutcomes: 'Students will learn HR processes, gain exposure to talent acquisition, and understand corporate policy implementation.',
      requirements: ['Bachelor of Science in Business Administration or related course', 'Good communication skills', 'OJT endorsement letter from school', 'Medical certificate'],
      supervisor: 'Ms. Joy Alcantara',
      supervisorContact: 'jalcantara@techcorp.ph',
      startDate: 'Apr 15, 2026',
      status: 'full',
      endorsed: 1,
      deployed: 1,
      posted: 'Mar 28, 2026',
    },
    {
      id: 4,
      department: 'Marketing Department',
      slots: 2,
      slotsRemaining: 2,
      preferredCourse: 'Bachelor of Science in Business Administration',
      duration: '3 months (486 hours)',
      schedule: 'Full Day · Mon–Fri',
      tasks: 'Social media content creation, market research assistance, campaign monitoring, and analytics reporting.',
      learningOutcomes: 'Students will apply marketing theories in live campaigns, practice data analysis, and develop digital marketing skills.',
      requirements: ['Bachelor of Science in Business Administration or related course', 'Creative writing skills', 'OJT endorsement letter from school'],
      supervisor: 'Mr. Nico Fajardo',
      supervisorContact: 'nfajardo@techcorp.ph',
      startDate: 'Jun 2, 2026',
      status: 'draft',
      endorsed: 0,
      deployed: 0,
      posted: null,
    },
  ],

  /* ── OJT Trainees ── */
  'ojt-trainees': [
    {
      id: 1,
      name: 'Anna Bautista',
      initials: 'AB',
      course: 'Bachelor of Science in Information Technology',
      university: 'CHMSU',
      department: 'IT Department',
      startDate: 'Feb 3, 2026',
      endDate: 'May 2, 2026',
      hoursRequired: 486,
      hoursRendered: 312,
      status: 'Active',
      contactNumber: '09171234567',
      email: 'anna.bautista@chmsu.edu.ph',
      schoolSupervisor: 'Prof. Lorena Vega',
      schoolSupervisorContact: 'l.vega@chmsu.edu.ph',
      schedule: 'Mon–Fri, 8:00 AM – 5:00 PM',
      tasks: [
        { date: 'Mar 1, 2026', task: 'Developed landing page component for Company Portal', hours: 8 },
        { date: 'Mar 3, 2026', task: 'Assisted in database schema design review', hours: 8 },
        { date: 'Mar 5, 2026', task: 'Performed UI testing and bug reporting', hours: 8 },
        { date: 'Mar 10, 2026', task: 'Created documentation for API endpoints', hours: 6 },
      ],
      attendance: [
        { date: 'Apr 14, 2026', timeIn: '8:02 AM', timeOut: '5:00 PM', hours: 8, remarks: 'Present' },
        { date: 'Apr 15, 2026', timeIn: '8:00 AM', timeOut: '5:00 PM', hours: 8, remarks: 'Present' },
        { date: 'Apr 16, 2026', timeIn: '8:15 AM', timeOut: '5:00 PM', hours: 7.75, remarks: 'Late' },
        { date: 'Apr 17, 2026', timeIn: '—', timeOut: '—', hours: 0, remarks: 'Absent – Sick Leave' },
        { date: 'Apr 18, 2026', timeIn: '8:00 AM', timeOut: '5:00 PM', hours: 8, remarks: 'Present' },
      ],
      documents: [
        { name: 'Endorsement Letter', status: 'Received' },
        { name: 'Parent Consent Form', status: 'Received' },
        { name: 'Waiver', status: 'Received' },
        { name: 'Medical Certificate', status: 'Pending' },
      ],
      evaluation: {
        midterm: null,
        final: null,
      },
    },
    {
      id: 2,
      name: 'Renz de la Cruz',
      initials: 'RC',
      course: 'Bachelor of Science in Accountancy',
      university: 'CHMSU',
      department: 'Accounting Department',
      startDate: 'Jan 6, 2026',
      endDate: 'Apr 4, 2026',
      hoursRequired: 240,
      hoursRendered: 240,
      status: 'Completed',
      contactNumber: '09281234567',
      email: 'renz.delacruz@chmsu.edu.ph',
      schoolSupervisor: 'Prof. Analyn Soriano',
      schoolSupervisorContact: 'a.soriano@chmsu.edu.ph',
      schedule: 'Mon–Sat, 8:00 AM – 12:00 PM',
      tasks: [
        { date: 'Feb 10, 2026', task: 'Assisted in monthly financial report preparation', hours: 4 },
        { date: 'Feb 12, 2026', task: 'Updated accounts receivable records', hours: 4 },
        { date: 'Mar 4, 2026', task: 'Prepared bank reconciliation worksheet', hours: 4 },
        { date: 'Mar 15, 2026', task: 'Encoded journal entries for March transactions', hours: 4 },
      ],
      attendance: [
        { date: 'Apr 1, 2026', timeIn: '8:00 AM', timeOut: '12:00 PM', hours: 4, remarks: 'Present' },
        { date: 'Apr 2, 2026', timeIn: '8:00 AM', timeOut: '12:00 PM', hours: 4, remarks: 'Present' },
        { date: 'Apr 3, 2026', timeIn: '8:00 AM', timeOut: '12:00 PM', hours: 4, remarks: 'Present' },
        { date: 'Apr 4, 2026', timeIn: '8:00 AM', timeOut: '12:00 PM', hours: 4, remarks: 'Present' },
      ],
      documents: [
        { name: 'Endorsement Letter', status: 'Received' },
        { name: 'Parent Consent Form', status: 'Received' },
        { name: 'Waiver', status: 'Received' },
        { name: 'Medical Certificate', status: 'Received' },
      ],
      evaluation: {
        midterm: {
          technical: 4,
          professionalism: 5,
          punctuality: 4,
          communication: 4,
          initiative: 3,
          qualityOfWork: 4,
          comments: 'Renz is a diligent worker with excellent attention to detail. Shows great professionalism in the workplace.',
          recommendation: 'Passed OJT',
          submittedBy: 'Ms. Sarah Chen',
          submittedDate: 'Feb 28, 2026',
        },
        final: {
          technical: 5,
          professionalism: 5,
          punctuality: 5,
          communication: 4,
          initiative: 4,
          qualityOfWork: 5,
          comments: 'Renz performed exceptionally throughout the OJT period. A model trainee who consistently delivered high-quality work.',
          recommendation: 'Passed OJT',
          submittedBy: 'Ms. Sarah Chen',
          submittedDate: 'Apr 4, 2026',
        },
      },
    },
    {
      id: 3,
      name: 'Christine Go',
      initials: 'CG',
      course: 'Bachelor of Science in Business Administration',
      university: 'CHMSU',
      department: 'Human Resources',
      startDate: 'Apr 15, 2026',
      endDate: 'Jul 12, 2026',
      hoursRequired: 486,
      hoursRendered: 8,
      status: 'Active',
      contactNumber: '09351234567',
      email: 'christine.go@chmsu.edu.ph',
      schoolSupervisor: 'Prof. Kevin Torres',
      schoolSupervisorContact: 'k.torres@chmsu.edu.ph',
      schedule: 'Mon–Fri, 8:00 AM – 5:00 PM',
      tasks: [
        { date: 'Apr 15, 2026', task: 'Company orientation and policy briefing', hours: 8 },
      ],
      attendance: [
        { date: 'Apr 15, 2026', timeIn: '8:00 AM', timeOut: '5:00 PM', hours: 8, remarks: 'Present' },
      ],
      documents: [
        { name: 'Endorsement Letter', status: 'Received' },
        { name: 'Parent Consent Form', status: 'Received' },
        { name: 'Waiver', status: 'Pending' },
        { name: 'Medical Certificate', status: 'Pending' },
      ],
      evaluation: {
        midterm: null,
        final: null,
      },
    },
  ],

  /* ── Analytics / Statistics ── */
  'analytics/overview': {
    hiringFunnel: {
      applied: 147,
      screened: 89,
      interviewed: 34,
      offered: 12,
      hired: 5,
    },
    monthlyApplications: [
      { month: 'Oct', count: 42 },
      { month: 'Nov', count: 58 },
      { month: 'Dec', count: 35 },
      { month: 'Jan', count: 67 },
      { month: 'Feb', count: 91 },
      { month: 'Mar', count: 147 },
    ],
    topSources: [
      { source: 'CHMSU Portal', count: 89 },
      { source: 'LinkedIn', count: 31 },
      { source: 'JobStreet', count: 18 },
      { source: 'Referral', count: 9 },
    ],
    departmentBreakdown: [
      { department: 'Engineering', openPositions: 3, applicants: 62, filled: 4, avgDays: 21 },
      { department: 'Design', openPositions: 1, applicants: 19, filled: 1, avgDays: 14 },
      { department: 'QA', openPositions: 0, applicants: 42, filled: 2, avgDays: 16 },
      { department: 'Infrastructure', openPositions: 1, applicants: 24, filled: 0, avgDays: null },
    ],
    kpiMetrics: [
      { label: 'Avg. Time to Hire', value: '18 days', icon: 'clock', color: '#4A6CF7', trend: '-3 days' },
      { label: 'Cost per Hire', value: '₱8,500', icon: 'dollarSign', color: '#10B981', trend: '-₱1,200' },
      { label: 'Interview-to-Offer', value: '35%', icon: 'zap', color: '#F59E0B', trend: '+5%' },
      { label: 'Offer Acceptance', value: '83%', icon: 'checkCircle', color: '#6366F1', trend: '+8%' },
    ],
    ojtAnalytics: {
      ojtKpis: [
        { label: 'OJT Slots Posted',  value: '5',     icon: 'graduationCap', color: '#4A6CF7', trend: '+2 this month' },
        { label: 'Total Applicants',  value: '38',    icon: 'users',          color: '#10B981', trend: '+12 vs last mo.' },
        { label: 'Active Trainees',   value: '6',     icon: 'userCheck',      color: '#F59E0B', trend: '' },
        { label: 'Acceptance Rate',   value: '15.8%', icon: 'zap',            color: '#8B5CF6', trend: '' },
      ],
      ojtFunnel: {
        interested: 38,
        endorsed:   14,
        accepted:   6,
        rejected:   5,
      },
      monthlyOjtInterests: [
        { month: 'Oct', count: 3  },
        { month: 'Nov', count: 7  },
        { month: 'Dec', count: 5  },
        { month: 'Jan', count: 9  },
        { month: 'Feb', count: 11 },
        { month: 'Mar', count: 14 },
      ],
      programBreakdown: [
        { program: 'Bachelor of Science in Information Technology',   count: 18 },
        { program: 'Bachelor of Science in Computer Science',        count:  9 },
        { program: 'Bachelor of Science in Business Administration', count:  6 },
        { program: 'Bachelor of Science in Accountancy',             count:  5 },
      ],
      activeTrainees: [
        { name: 'Maria Santos',  email: 'maria.santos@chmsu.edu.ph',  program: 'Bachelor of Science in Information Technology', year_level: '4th Year', started_at: 'Jan 15, 2026', hours_rendered: 267 },
        { name: 'Juan Cruz',     email: 'juan.cruz@chmsu.edu.ph',     program: 'Bachelor of Science in Computer Science',      year_level: '3rd Year', started_at: 'Feb 1, 2026',  hours_rendered: 213 },
        { name: 'Ana Reyes',     email: 'ana.reyes@chmsu.edu.ph',     program: 'Bachelor of Science in Information Technology', year_level: '4th Year', started_at: 'Feb 10, 2026', hours_rendered: 198 },
        { name: 'Carlo Mendoza', email: 'carlo.mendoza@chmsu.edu.ph', program: 'Bachelor of Science in Business Administration', year_level: '3rd Year', started_at: 'Mar 3, 2026',  hours_rendered: 152 },
        { name: 'Lea Tan',       email: 'lea.tan@chmsu.edu.ph',       program: 'Bachelor of Science in Accountancy',          year_level: '4th Year', started_at: 'Mar 17, 2026', hours_rendered: 104 },
        { name: 'Nico Villena',  email: 'nico.villena@chmsu.edu.ph',  program: 'Bachelor of Science in Computer Science',      year_level: '3rd Year', started_at: 'Apr 2, 2026',  hours_rendered:  58 },
      ],
    },
  },
};
